openapi: 3.0.1
info:
  title: Data-service API
  version: 1.0.0

paths:
  /students:
    post:
      tags:
        - StudentData
      summary: Создать студента
      operationId: createStudentDataInData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentDataCreateRequest'
      responses:
        '200':
          description: Студент создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDataResponse'

  /students/{id}:
    get:
      tags:
        - StudentData
      summary: Получить данные студента по id
      operationId: getStudentDataByIdFromData
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Найденный студент
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDataResponse'
        '404':
          description: Студент не найден

components:
  schemas:
    StudentDataCreateRequest:
      type: object
      required:
        - fullName
        - passport
      properties:
        fullName:
          type: string
          description: 'ФИО студента'
        passport:
          type: string
          description: 'Серия и номер паспорта студента'

    StudentDataResponse:
      type: object
      required:
        - id
        - fullName
        - passport
      properties:
        id:
          type: integer
          format: int64
        fullName:
          type: string
        passport:
          type: string
